### ISSUE TITLE
Session Detached (reason=attach timeout).

### ISSUE THREAD

**Issue by Channe** [neil-wu/CatFrida#2]
iPhone 7P 13.5.1，已通过 checkra1n 越狱
Mac OS X 10.15.7 (19H15)
试了几个 App 都是这样

**Comment by neil-wu** [comment]
> iPhone 7P 13.5.1，已通过 checkra1n 越狱
> Mac OS X 10.15.7 (19H15)
> 试了几个 App 都是这样

iPhone上是否已从cydia 安装frida server , 参考此 https://frida.re/docs/ios/#with-jailbreak

**Comment by Channe** [comment]
> > iPhone 7P 13.5.1，已通过 checkra1n 越狱
> > Mac OS X 10.15.7 (19H15)
> > 试了几个 App 都是这样
> 
> iPhone上是否已从cydia 安装frida server , 参考此 https://frida.re/docs/ios/#with-jailbreak

**Comment by Channe** [comment]
安装frida server 后可以了！谢谢

**Comment by neil-wu** [comment]
Happy Hacking
