### ISSUE TITLE
请问，能否适配一下MacOS 10.14.6系统 软件在这个版本无法运行

### ISSUE THREAD

**Issue by udpsec** [neil-wu/CatFrida#3]

**Comment by neil-wu** [comment]
需要手动签名一下，参考README的签名命令

**Comment by neil-wu** [comment]
我这缺少10.14的系统无法测试。可以下载源码编译一下呢

**Comment by udpsec** [comment]
好的，谢谢。

**Comment by neil-wu** [comment]
> 好的，谢谢。

我将版本降为10.14重新打包了一个  [放在dropbox里，可以试试](https://www.dropbox.com/s/4x7ku6yw9pl3s8o/CatFrida.app_10.14.zip?dl=0)

**Comment by udpsec** [comment]
好的，我试一下

**Comment by udpsec** [comment]
测试成功，可以使用

**Comment by neil-wu** [comment]
感谢测试 👍
