### ISSUE TITLE
大佬辛苦了～有没有中文详细使用说明吗？

### ISSUE THREAD

**Issue by s88101088** [neil-wu/CatFrida#4]
大佬辛苦了～有没有中文详细使用说明吗？
如果有的话再麻烦您提供OK吗？万分感激～

**Comment by neil-wu** [comment]
可以查看[屏幕截图里的功能](https://github.com/neil-wu/CatFrida/tree/main/Screenshots)。
只要设备上按照Frida官方教程配置好Frida server，这个app就是点点点就行

**Comment by s88101088** [comment]
谢你了大佬

從我的iPhone傳送

neilwu <notifications@github.com> 於 2021年1月27日 下午9:59 寫道：

﻿

可以查看屏幕截图里的功能<https://github.com/neil-wu/CatFrida/tree/main/Screenshots>。
只要设备上按照Frida官方教程配置好Frida server，这个app就是点点点就行
